languageCode = 'it'
defaultContentLanguage = 'it'
title = 'Ingegneria Informatica'
enableGitInfo = true


[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/VaiTon/UniBo-IngInfo'
BookEditPath = '/tree/main/'
BookDateFormat = 'Monday, January 2, 2006'
BookServiceWorker = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
